services:
  postgres:
    image: "postgres:16.1"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gerador_certificado
    ports:
      - "5432:5432"
    networks:
      - diploma_network
    volumes:
      - ./postgres/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@user.com
      PGADMIN_DEFAULT_PASSWORD: 1234
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
    depends_on:
      - postgres
    networks:
      - diploma_network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - diploma_network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "3000:3000"
    networks:
      - diploma_network

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - ./worker/pdf_files:/app/worker/pdf_files
    networks:
      - diploma_network

networks:
  diploma_network:
    driver: bridge

volumes:
  certificado_storage:
